---
name: AudioFile-Info-MP4-Info
version: 0.5
author:
  - 'Simon Wistow, E<lt>simon@thegestalt.orgE<gt>'
abstract: Perl extension to get info from MP4 files.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  AudioFile::Info: 0
  MP4::Info: 0
  perl: 5.6.0
build_requires:
  Module::Build: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
